name: Go Tests and Benchmarks

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests and benchmarks
      run: go test -bench=.
      